force-app/main/default/objects/mappmct__EngageGroupMapping__c/mappmct__EngageGroupMapping__c.object-meta.xml
<CustomObject>
    <label>EngageGroupMapping</label>
    <nameField>
        <label>EngageGroupMapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EngageGroupMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/mappmct__EngageGroupMapping__c/fields/mappmct__EngageGroupId__c.field-meta.xml
<CustomField>
    <fullName>mappmct__EngageGroupId__c</fullName>
    <label>EngageGroupId</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CampaignSaveCallout.cls
public class CampaignSaveCallout {
    @future(callout=true)
    public static void saveCampaign(String id, String name) {
        Long engageGroupId = new EngageApiClient().createGroup(name);
        if (engageGroupId != null) {
            mappmct__EngageGroupMapping__c engageGroupMapping = new mappmct__EngageGroupMapping__c(mappmct__CampaignId__c = id, mappmct__EngageGroupId__c = engageGroupId, name = id + '-' + String.valueOf(engageGroupId));
            insert engageGroupMapping;
        }
    }
}