force-app/main/default/objects/mappmct__EngageCustomFields__c/mappmct__EngageCustomFields__c.object-meta.xml
<CustomObject>
    <label>EngageCustomFields</label>
    <nameField>
        <label>EngageCustomFields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EngageCustomFields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/mappmct__EngageCustomFields__c/fields/mappmct__FieldType__c.field-meta.xml
<CustomField>
    <fullName>mappmct__FieldType__c</fullName>
    <label>FieldType</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomFieldsHelper.cls
public class CustomFieldsHelper {
    
    public static Map<String, String> getCustomLeadFields(Lead ld) {
        Map<String, String> customFields = new Map<String, String>();
        mappmct__EngageCustomFields__c[] fields = [SELECT Name FROM mappmct__EngageCustomFields__c WHERE mappmct__FieldType__c = 'Lead'];
        for (mappmct__EngageCustomFields__c field : fields) {
            if (ld.get(field.Name) != null) {
                customFields.put(field.Name, ld.get(field.Name).toString());
            }
        }
        return customFields;
    }

    public static Map<String, String> getCustomContactFields(Contact ct) {
        Map<String, String> customFields = new Map<String, String>();
        mappmct__EngageCustomFields__c[] fields = [SELECT Name FROM mappmct__EngageCustomFields__c WHERE mappmct__FieldType__c = 'Contact'];
        for (mappmct__EngageCustomFields__c field : fields) {
            if (ct.get(field.Name) != null) {
                customFields.put(field.Name, ct.get(field.Name).toString());
            }
        }
        return customFields;
    }
}