force-app/main/default/objects/mappmct__engage_integration__c/mappmct__engage_integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>engage_integration</label>
</CustomObject>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__lead_group__c.field-meta.xml
<CustomField>
    <fullName>mappmct__lead_group__c</fullName>
    <label>lead_group</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mappmct__EngageGroupMapping__c/mappmct__EngageGroupMapping__c.object-meta.xml
<CustomObject>
    <label>EngageGroupMapping</label>
    <nameField>
        <label>EngageGroupMapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EngageGroupMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/mappmct__EngageGroupMapping__c/fields/mappmct__EngageGroupId__c.field-meta.xml
<CustomField>
    <fullName>mappmct__EngageGroupId__c</fullName>
    <label>EngageGroupId</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadSaveCallout.cls
public class LeadSaveCallout {

	@future(callout=true)
    public static void saveLead(String email, String id, String mobilePhone, String firstName, String lastName, String salutation, String postalCode, 
            String country, String company, String leadSource, String status, String rating, Map<String, String> customFields) {

        new EngageApiClient().saveContact(EntityType.LEAD, id, email, mobilePhone, firstName, lastName, salutation, null, postalCode, null, country,
            company, leadSource, status, rating, customFields);
    }

    @future(callout=true)
    public static void deleteLead(String email) {
        EngageApiClient engageApiClient = new EngageApiClient();

        mappmct__engage_integration__c integrationSettingsFrom = SettingsController.getIntegrationSettings();
        engageApiClient.unsubscribeContact(email, integrationSettingsFrom.mappmct__lead_group__c);

        List<mappmct__EngageGroupMapping__c> engageGroupMappings = [SELECT mappmct__EngageGroupId__c FROM mappmct__EngageGroupMapping__c];
        for (mappmct__EngageGroupMapping__c engageGroupMapping : engageGroupMappings) {
            engageApiClient.unsubscribeContact(email, String.valueOf(engageGroupMapping.mappmct__EngageGroupId__c));
        }
    }
}