force-app/main/default/objects/mappmct__engage_integration__c/mappmct__engage_integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>engage_integration</label>
</CustomObject>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__api_url__c.field-meta.xml
<CustomField>
    <fullName>mappmct__api_url__c</fullName>
    <label>api_url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__connection_status__c.field-meta.xml
<CustomField>
    <fullName>mappmct__connection_status__c</fullName>
    <label>connection_status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__integration_id__c.field-meta.xml
<CustomField>
    <fullName>mappmct__integration_id__c</fullName>
    <label>integration_id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__secret__c.field-meta.xml
<CustomField>
    <fullName>mappmct__secret__c</fullName>
    <label>secret</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mappmct__EngageGroupMapping__c/mappmct__EngageGroupMapping__c.object-meta.xml
<CustomObject>
    <label>EngageGroupMapping</label>
    <nameField>
        <label>EngageGroupMapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EngageGroupMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/mappmct__EngageGroupMapping__c/fields/mappmct__EngageGroupId__c.field-meta.xml
<CustomField>
    <fullName>mappmct__EngageGroupId__c</fullName>
    <label>EngageGroupId</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggersTest.cls
@isTest
public class TriggersTest {

    @TestSetup static void setup() {
        mappmct__engage_integration__c intc = new mappmct__engage_integration__c(mappmct__api_url__c = 'http://engage.com', 
            mappmct__integration_id__c = 'intid', mappmct__secret__c = 'sec', mappmct__connection_status__c = ConnectionStatus.DISCONNECTED.name());
        insert intc;  
    }

    @isTest static void testCampaignInsert() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EngageApiClientCalloutMock());

        Campaign campaign = new Campaign(name = 'MeinKampanien', type = 'Mapp Engage');
        insert campaign;
        
        Test.stopTest();
        
        mappmct__EngageGroupMapping__c engageGroupMapping = [SELECT mappmct__EngageGroupId__c FROM mappmct__EngageGroupMapping__c WHERE mappmct__CampaignId__c = :campaign.id];
        System.assertEquals(678, engageGroupMapping.mappmct__EngageGroupId__c);
    }

    @isTest static void testContactInsertUpdateDelete() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EngageApiClientCalloutMock());

        Contact contact = new Contact(email = 'dziobak@xx.xx', LastName = 'pandziobak');        
        insert contact;

        contact.LastName = 'pepe';
        update contact;
 
        delete contact;
        
        Test.stopTest();
    }

    @isTest static void testLeadInsertUpdateDelete() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EngageApiClientCalloutMock());

        Lead lead = new Lead(email = 'dziobak@xx.xx', company = 'mcdonalds', LastName = 'pandziobak');        
        insert lead;

        lead.lastName = 'pepe';
        update lead;

        delete lead;
        
        Test.stopTest();
    }

    @isTest static void testLeadMemberInsert() {
        Campaign campaign = new Campaign(name = 'MeinKampanien' + Datetime.now().millisecond(), type = 'Mapp Engage');
        insert campaign;      

        Lead lead = new Lead(email =  Datetime.now().millisecond() + 'doofenschmirtz@xx.xx', company = 'dei', LastName = 'heinz');        
        insert lead;

        mappmct__EngageGroupMapping__c engageGroupMapping = new mappmct__EngageGroupMapping__c(mappmct__CampaignId__c = campaign.id, mappmct__EngageGroupId__c = 1234);
        insert engageGroupMapping;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EngageApiClientCalloutMock());

        CampaignMember cm = new CampaignMember(CampaignId = campaign.id, LeadId = lead.id);
        insert cm;
        
        Test.stopTest();
    }

    @isTest static void testContactMemberInsert() {
        Campaign campaign = new Campaign(name = 'MeinKampanien' + Datetime.now().millisecond(), type = 'Mapp Engage');
        insert campaign;      

        Contact contact = new Contact(email =  Datetime.now().millisecond() + 'doofenschmirtz@xx.xx', LastName = 'heinz');        
        insert contact;

        mappmct__EngageGroupMapping__c engageGroupMapping = new mappmct__EngageGroupMapping__c(mappmct__CampaignId__c = campaign.id, mappmct__EngageGroupId__c = 1234);
        insert engageGroupMapping;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EngageApiClientCalloutMock());

        CampaignMember cm = new CampaignMember(CampaignId = campaign.id, ContactId = contact.id);
        insert cm;

        delete cm;
        
        Test.stopTest();
    }
}