force-app/main/default/objects/mappmct__engage_integration__c/mappmct__engage_integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>engage_integration</label>
</CustomObject>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__api_url__c.field-meta.xml
<CustomField>
    <fullName>mappmct__api_url__c</fullName>
    <label>api_url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__connection_status__c.field-meta.xml
<CustomField>
    <fullName>mappmct__connection_status__c</fullName>
    <label>connection_status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__integration_id__c.field-meta.xml
<CustomField>
    <fullName>mappmct__integration_id__c</fullName>
    <label>integration_id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__secret__c.field-meta.xml
<CustomField>
    <fullName>mappmct__secret__c</fullName>
    <label>secret</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailControllerTest.cls
@isTest
public class EmailControllerTest {
    
    @TestSetup static void setup() {
        mappmct__engage_integration__c intc = new mappmct__engage_integration__c(mappmct__api_url__c = 'http://engage.com', 
            mappmct__integration_id__c = 'intid', mappmct__secret__c = 'sec', mappmct__connection_status__c = ConnectionStatus.DISCONNECTED.name());
        insert intc;
    }

    @isTest static void testInstantiation() {
        Lead lead = new Lead(email = Datetime.now().millisecond() + 'lid@xx.xx', LastName = 'zdzich', Company = 'XXX');
        insert lead;

        Test.setMock(HttpCalloutMock.class, new EngageApiClientCalloutMock());        
        
        Test.startTest();

        ApexPages.currentPage().getParameters().put('id', lead.Id);

        EmailController emailController = new EmailController();
        System.assert(emailController.messages.size() == 2);

        Test.stopTest();
    }

    @isTest static void testSendSingle() {

        Lead lead = new Lead(email = Datetime.now().millisecond() + 'lid@xx.xx', LastName = 'zdzich', Company = 'XXX');
        insert lead;

        Test.setMock(HttpCalloutMock.class, new EngageApiClientCalloutMock());        
        
        Test.startTest();

        ApexPages.currentPage().getParameters().put('id', lead.Id);

        EmailController emailController = new EmailController();
        emailController.sendSingle();

        Test.stopTest();
    }

    @isTest static void testSendCampaign() {
        Lead lead = new Lead(email = Datetime.now().millisecond() + 'lid@xx.xx', LastName = 'zdzich', Company = 'XXX');
        insert lead;

        Test.setMock(HttpCalloutMock.class, new EngageApiClientCalloutMock());        
        
        Test.startTest();

        ApexPages.currentPage().getParameters().put('id', lead.Id);
        
        EmailController emailController = new EmailController();
        emailController.sendCampaign();

        Test.stopTest();
    }
}