force-app/main/default/objects/mappmct__engage_integration__c/mappmct__engage_integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>engage_integration</label>
</CustomObject>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__api_url__c.field-meta.xml
<CustomField>
    <fullName>mappmct__api_url__c</fullName>
    <label>api_url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__connection_status__c.field-meta.xml
<CustomField>
    <fullName>mappmct__connection_status__c</fullName>
    <label>connection_status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__integration_id__c.field-meta.xml
<CustomField>
    <fullName>mappmct__integration_id__c</fullName>
    <label>integration_id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__lead_group__c.field-meta.xml
<CustomField>
    <fullName>mappmct__lead_group__c</fullName>
    <label>lead_group</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mappmct__engage_integration__c/fields/mappmct__secret__c.field-meta.xml
<CustomField>
    <fullName>mappmct__secret__c</fullName>
    <label>secret</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SettingsControllerTest.cls
@isTest
public class SettingsControllerTest {

    @TestSetup static void setup() {
        mappmct__engage_integration__c intc = new mappmct__engage_integration__c(mappmct__api_url__c = 'http://engage.com', 
            mappmct__integration_id__c = 'intid', mappmct__secret__c = 'sec', mappmct__connection_status__c = ConnectionStatus.DISCONNECTED.name());
        insert intc;
    }

    @isTest static void testSaveAndConnect() {
        Test.setMock(HttpCalloutMock.class, new EngageApiClientCalloutMock());        
        
        Test.startTest();

        ConnectionInfo connectionInfo = new ConnectionInfo();
        connectionInfo.connectionStatus = ConnectionStatus.DISCONNECTED;
        connectionInfo.error = false;
        connectionInfo.groupNamesAndIds = new Map<String, Long>();
        
        SettingsController settingsController = new SettingsController();
        settingsController.save();
       
        Test.stopTest();
        List<mappmct__engage_integration__c> settings = [SELECT id, mappmct__api_url__c, mappmct__integration_id__c, mappmct__secret__c, mappmct__lead_group__c, mappmct__connection_status__c FROM mappmct__engage_integration__c];
		mappmct__engage_integration__c integrationSettings = settings.get(0);
        System.assert(settings.size() == 1);     
    }
}